os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - msbuild /t:restore /bl:restore.binlog
  - msbuild /t:build,pack /bl

# since this requires launching VS and special UI permissions
test: off

deploy:
  - provider: NuGet
    api_key:
      secure: 7MS5+XWaFchMXFqzgneQCqo9U0DlxiPXe/KWWUnbCBDEizVn06EjdQZkWu1gbNOJ
    artifact: /.*\.nupkg/
    on:
      branch: master
      
nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: 'bin\*.nupkg'
    name: Packages

  - path: '*.binlog'
    name: Logs
