os: Visual Studio 2017

init:
  - git config --global core.autocrlf input

build_script:
  - msbuild /t:restore /bl:restore.binlog
  - msbuild /t:build /bl:build.binlog

# since this requires launching VS and special UI permissions
test: off

nuget:
  project_feed: true
  disable_publish_on_pr: true
  
artifacts:
  - path: 'bin\*.nupkg'
    name: Packages

  - path: '*.binlog'
    name: Logs
